workflows:
  flutter-release:
    name: Flutter Clean App Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Unzip lib folder
        script: unzip lib.zip -d lib
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk